---
- hosts: all
  gather_facts: no
  roles:
    - common
    - users
    - neovim
    - docker
- hosts: localhost
  connection: local
- hosts: dev
  tasks:
    - name: include secret vars
      include_vars: 'secret_vars/all.yml'
  roles:
    - common
    - users
    - docker
    - openvpn
    - neovim
