---
- name: get dotfiles
  git:
    repo: https://github.com/kosmatov/dotfiles
    dest: "{{ item.home }}/dotfiles"
  ignore_errors: true
  become: true
  become_user: "{{ item.name }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: install dotfiles
  command: dotfiles/install creates=.config/nvim/
  args:
    chdir: "{{ item.home }}"
  become: true
  become_user: "{{ item.name }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
