---
- include: users.yml
  become: true
- include: dotfiles.yml
  vars:
    users:
      - name: "{{ lookup('env', 'USER') }}"
        home: "/home/{{ lookup('env', 'USER') }}.linux"
  tags:
    - lima
- include: dotfiles.yml
  vars:
    users:
      - name: vagrant
        home: /home/vagrant
  tags:
    - vagrant
