---
- import_tasks: users.yml
- import_tasks: dotfiles.yml
  vars:
    users:
      - name: "{{ lookup('env', 'USER') }}"
        home: "/home/{{ lookup('env', 'USER') }}.linux"
  tags:
    - lima
- import_tasks: dotfiles.yml
  vars:
    users:
      - name: vagrant
        home: /home/vagrant
  tags:
    - vagrant
