---
- name: install base packages
  apt:
    state: latest
    name:
      - zsh
      - git
      - curl
      - tcpdump
      - telnet
      - net-tools
      - clang
      - make
      - fzf
      - ripgrep
      - fd-find
      - pass
  become: true
