---
- name: install base packages
  apt:
    state: latest
    name:
      - zsh
      - git
      - curl
      - tcpdump
      - telnet
      - net-tools
      - clang
      - make

# - name: enable chronyd
#   service: name=chronyd enabled=yes state=started
#   tags:
#     - vagrant

# - name: add exports
#   template: src=templates/exports dest=/etc/exports
#   tags:
#     - vagrant

# - name: enable NFS service
#   service: name=nfs-server enabled=yes state=started
#   tags:
#     - vagrant
