---
- name: Install base packages
  dnf:
    state: latest
    name:
      - epel-release
      - zsh
      - git
      - curl
      - tcpdump
      - telnet
      - net-tools
      - bind-utils
      - kernel-devel
      - chrony
      - make

- name: Detect ZSH path
  shell: which zsh
  register: which_zsh
  changed_when: false

- name: Change user shell
  user: name=vagrant shell={{ which_zsh.stdout }}

- name: Add vagrant to dialout group
  user:
    name: vagrant
    groups: dialout
    append: yes

- name: Enable chronyd
  service: name=chronyd enabled=yes state=started

- name: Add exports
  template: src=templates/exports dest=/etc/exports
