---
- name: Create docker disk partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
  become: true

- name: Create home disk partition
  parted:
    device: /dev/sdc
    number: 1
    state: present
  become: true

- name: Create docker fs
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
  become: true

- name: Create home fs
  filesystem:
    fstype: xfs
    dev: /dev/sdc1
  become: true
  register: home_fs_created

- name: Temporary mount home
  mount:
    path: /mnt/home
    fstype: xfs
    src: /dev/sdc1
    state: mounted
  become: true
  register: temporary_home_mounted
  when: home_fs_created.changed

- name: Create vagrant home
  file:
    path: /mnt/home/vagrant/
    group: vagrant
    owner: vagrant
    mode: '0700'
    state: directory
  become: true
  register: vagrant_home_created
  when: temporary_home_mounted.changed

- name: Copy vagrant home
  copy:
    src: /home/vagrant/
    remote_src: yes
    dest: /mnt/home/vagrant/
    group: vagrant
    owner: vagrant
  when: vagrant_home_created.changed

- name: Umount temporary home
  mount:
    path: /mnt/home
    state: absent
  become: true

- name: Mount docker fs
  mount:
    path: /var/lib/docker
    src: /dev/sdb1
    fstype: xfs
    state: mounted
  become: true

- name: Mount home fs
  mount:
    path: /home
    src: /dev/sdc1
    fstype: xfs
    state: mounted
  become: true
