---
- name: Add docker repo
  template: src=templates/docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo

- name: Add docker-ce
  block:
    - name: Add latest
      dnf: name=docker-ce state=latest update_cache=true
  rescue:
    - name: Add --nobest
      shell:
        cmd: dnf install --nobest docker-ce
        warn: false

- name: Detect docker-compose latest release tag
  shell:
    cmd: curl -ILs https://github.com/docker/compose/releases/latest | grep releases/tag | cut -d/ -f8
    warn: false
  register: docker_compose_release_tag
  changed_when: false

- name: Add docker-compose
  shell:
    cmd: curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_release_tag.stdout }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    creates: /usr/local/bin/docker-compose

- name: Start docker service
  service: name=docker enabled=yes state=started

- name: Add vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
