---
- import_tasks: disks.yml
  tags:
    - vagrant
- import_tasks: common.yml
  tags:
    - lima
    - vagrant
- import_tasks: nginx.yml
  tags:
    - lima
    - vagrant
- import_tasks: ansible.yml
  tags:
    - lima
    - vagrant
