---
- name: install docker
  apt:
    state: latest
    name:
      - docker
      - docker-compose

- name: start docker service
  service: name=docker enabled=yes state=started

- name: add users to docker group
  user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
