---
- name: install dependencies
  apt:
    state: latest
    name:
      - neovim
      - gcc
      - python3-dev
      - python3-pip

- name: install neovim-remote
  pip: name=neovim-remote state=latest
