---
- name: install dependencies
  apt:
    state: latest
    name:
      - cmake
      - gettext
      - gcc
      - python3-dev
      - python3-pip
  become: true

- name: get neovim source
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: /root/neovim
    refspec: stable
    force: true
  become: true

- name: checkout to stable
  command:
    chdir: /root/neovim
    cmd: git checkout stable
  become: true

- name: build and install neovim
  command:
    chdir: /root/neovim
    cmd: |
      make CMAKE_BUILD_TYPE=RelWithDebInfo install
    creates: /usr/local/bin/nvim
  become: true

- name: ensure pip config dir exists
  file:
    path: ~/.config/pip/
    state: directory
  become: true

- name: add pip config
  copy:
    src: files/pip.conf
    dest: ~/.config/pip/pip.conf
    force: no
  become: true

- name: install neovim-remote
  pip: name=neovim-remote state=latest
  become: true

- name: install aider-chat
  pip: name=aider-chat state=absent
  become: true
